repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect-secrets (pre-commit)
        args: ["--baseline", ".secrets.baseline", "--exclude-files", "^\\.env$"]
        exclude: |
          (?x)^(
            \.venv/|
            .*\.lock$|
            .*\.md$|
            .*\.toml$|
            .*\.yaml$|
            .*\.yml$|
            .*\.txt$
          )
  - repo: local
    hooks:
      - id: pytest-on-push
        name: pytest (on push)
        entry: uv run pytest -q
        language: system
        pass_filenames: false
        stages: [pre-push]
