name: CI

on:
  pull_request:
  push:
    branches: [ main, master, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Sync dependencies (with dev extras)
        run: uv sync --extra dev

      - name: Pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Run tests with coverage (>=80%)
        run: |
          uv run pytest -q --cov=nexus_agent --cov-report=term-missing --cov-fail-under=80

  zap-baseline:
    # Optional: runs a ZAP baseline scan if ZAP_TARGET is provided
    if: ${{ github.event_name == 'pull_request' && vars.ZAP_TARGET != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ vars.ZAP_TARGET }}
          rules_file_name: '.zap/rules.tsv'
          allow_issue_writing: false
          cmd_options: '-a'
